# Generated by Django 6.0.4 on 2026-05-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="alunos",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="professor",
        ),
        migrations.AddField(
            model_name="aluno",
            name="curso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="escola.curso",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="curso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professores",
                to="escola.curso",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(upload_to="cursos/"),
        ),
    ]
