# Generated by Django 6.0.4 on 2026-05-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_remove_curso_alunos_remove_curso_professor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="curso",
        ),
        migrations.AddField(
            model_name="curso",
            name="alunos",
            field=models.ManyToManyField(related_name="cursos", to="escola.aluno"),
        ),
        migrations.AddField(
            model_name="curso",
            name="professor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="escola.professor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.URLField(),
        ),
    ]
