# Generated by Django 6.0.4 on 2026-04-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("area_especializacao", models.CharField(max_length=150)),
                ("pagina_pessoal_url", models.URLField(blank=True)),
                ("foto", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=20)),
                ("grau", models.CharField(max_length=50)),
                ("departamento", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("duracao_anos", models.PositiveIntegerField()),
                ("imagem", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("entidade_alvo", models.CharField(max_length=150)),
                ("descricao_processo", models.TextField()),
                ("decisoes_modelacao", models.TextField()),
                ("erros_encontrados", models.TextField()),
                ("correcoes_realizadas", models.TextField()),
                ("justificacao_opcoes", models.TextField()),
                ("uso_ia", models.TextField()),
                ("contributo_ia", models.TextField()),
                ("foto_der", models.URLField(blank=True)),
                ("data_registo", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("website_oficial", models.URLField(blank=True)),
                ("logo", models.URLField(blank=True)),
                ("nivel_proficiencia", models.CharField(max_length=50)),
                ("nivel_interesse", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnologias",
                        to="portfolio.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("instituicao", models.CharField(max_length=150)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("certificado_url", models.URLField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("autor", models.CharField(max_length=150)),
                ("ano", models.PositiveIntegerField()),
                ("resumo", models.TextField()),
                ("area_tematica", models.CharField(max_length=150)),
                ("url_documento", models.URLField(blank=True)),
                ("classificacao_interesse", models.CharField(max_length=50)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("objetivos", models.TextField()),
                ("conhecimentos_aplicados", models.TextField()),
                ("github_url", models.URLField(blank=True)),
                ("imagem", models.URLField(blank=True)),
                ("estado", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.categoria",
                    ),
                ),
                (
                    "tfcs",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tfc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=20)),
                ("ano_curricular", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.DecimalField(decimal_places=1, max_digits=4)),
                ("descricao", models.TextField()),
                ("imagem", models.URLField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
