# Generated by Django 6.0.4 on 2026-04-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="decisoes_modelacao",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="descricao_processo",
        ),
        migrations.AlterField(
            model_name="makingof",
            name="foto_der",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/der/"),
        ),
    ]
