# Generated by Django 6.0.4 on 2026-04-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_makingof_decisoes_modelacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoMakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="makingof/der/")),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="portfolio.makingof",
                    ),
                ),
            ],
        ),
    ]
