# Generated by Django 6.0.4 on 2026-05-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_fotomakingof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotomakingof",
            name="imagem",
            field=models.ImageField(upload_to="makingof/fotos/"),
        ),
    ]
